export const FETCH_EVENTS = "FETCH_EVENTS";
export const UPDATE_SELECTED_EVENT = "UPDATE_SELECTED_EVENT";
export const UPDATE_HOVERED_EVENT = "UPDATE_HOVERED_EVENT";
export const FETCH_NUMBER_OF_PAGES = "FETCH_NUMBER_OF_PAGES";
export const CHANGE_SELECTED_EVENT = "CHANGE_SELECTED_EVENT";
export const FETCH_200_EVENTS = "FETCH_200_EVENTS";
export const CHANGE_SEARCH_RESULTS = "CHANGE_SEARCH_RESULTS";